// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5aHiPSzUe5svnLqh3zl4aZMHhDF-fmQ',
    appId: '1:752318178337:web:2f145bbc89cc9837136f60',
    messagingSenderId: '752318178337',
    projectId: 'data-store-app-b5e5c',
    authDomain: 'data-store-app-b5e5c.firebaseapp.com',
    storageBucket: 'data-store-app-b5e5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEvwJPa0ObEkp40Z7-2qKdlC17b3kv3N4',
    appId: '1:752318178337:android:175a656d7ae6afc6136f60',
    messagingSenderId: '752318178337',
    projectId: 'data-store-app-b5e5c',
    storageBucket: 'data-store-app-b5e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTx9aoNaVmBmrzOZni5fPI4tbBOFZ8leA',
    appId: '1:752318178337:ios:769aef9af0a94770136f60',
    messagingSenderId: '752318178337',
    projectId: 'data-store-app-b5e5c',
    storageBucket: 'data-store-app-b5e5c.appspot.com',
    iosClientId: '752318178337-jo7kh8nlc23qsobqsiid2gr4hblqq0la.apps.googleusercontent.com',
    iosBundleId: 'com.example.app100x',
  );
}
